# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c513ce4bf48159bab8746462dc46ed960feb3a151ebfac32a8de7d3ea3c019055d4a8a01478676f2e0cfafc5098f6fcf9ac3f12225c3ba741d4949fe24038a5d

test:
  secret_key_base: 85b2e126300acbe8e6be8aa6b838508567ec2e64acb3b7703fd28a33537eab1585972baf86524a3687e2ccc8140cbd22f8a8453781b7bec062ea4e52bc34279d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
